Refactoring structure ando commands

diff --git a/bin/doravel b/bin/doravel
--- a/bin/doravel
+++ b/bin/doravel
@@ -1,7 +1,9 @@
 #!/bin/bash
 
 VERSION="1.0.0"
-DOCKER_CONTAINER=${DOCKER_CONTAINER:-0}
+DORAVEL_ISOLATED=${DORAVEL_ISOLATED:-0}
+DORAVEL_CONTAINER=${DORAVEL_CONTAINER:-0}
+DORAVEL_INSTALLED=${DORAVEL_INSTALLED:-0}
 
 function print_help {
     echo '
@@ -86,8 +88,10 @@ COMMANDS_ENVIRONMENT=(
 COMMANDS_DORAVEL=(
     "package"
     "upgrade"
+    "install"
     "update"
     "logout"
+    "doctor"
     "login"
     "setup"
     "fix"
@@ -128,7 +132,12 @@ ENV_NAME=$(sed 's/\*$//g' <<< "$ENV_NAME")
 ENV_FILE=$(find . -maxdepth 1 -name "$ENV_FILE" | head -n 1)
 
 if [[ $ENV_NAME == *"*"* ]]; then
-    echo "Environment name can't contain *"
+    echo "❌ Environment name can't contain *"
+    exit 0
+fi
+
+if [[ ! $ENV_NAME =~ ^[a-zA-Z0-9_-]+$ ]]; then
+    echo "❌ Environment name not valid"
     exit 0
 fi
 
@@ -156,7 +165,7 @@ DOCKER_COMPOSE_FILE=$(find . -maxdepth 1 -name "$DOCKER_COMPOSE_NAME.y*" | head 
 COMMAND_DOCKER_COMPOSE=$(echo " ${COMMANDS_DOCKER_COMPOSE[@]} " | grep -o " $COMMAND " | xargs)
 COMMAND_ENVIRONMENT=$(echo " ${COMMANDS_ENVIRONMENT[@]} " | grep -o " $COMMAND " | xargs)
 COMMAND_DORAVEL=$(echo " ${COMMANDS_DORAVEL[@]} " | grep -o " $COMMAND " | xargs)
-DORAVEL_IMAGE="byancode/doravel:$VERSION"
+DORAVEL_IMAGE="byancode/doravel:${VERSION}-latest"
 
 doravel_image_run() {
     docker run --rm -it -v .:/var/www $DORAVEL_IMAGE $@
@@ -191,9 +200,9 @@ if [ ! -z "$COMMAND_DORAVEL" ]; then
         VOLUMES=( "-v .:/var/www" )
         DOCKER_SOCKET_FILE="/var/run/docker.sock"
         if [ -S "$DOCKER_SOCKET_FILE" ]; then
-            VOLUMES+=( "-v /var/run/docker.sock:/var/run/docker.sock" )
+            VOLUMES+=( "-v $DOCKER_SOCKET_FILE:$DOCKER_SOCKET_FILE" )
         fi
-        docker run --rm -it ${VOLUMES[@]} $DORAVEL_IMAGE $@
+        docker run --rm -it ${VOLUMES[@]} -e "DORAVEL_ISOLATED=1" $DORAVEL_IMAGE $@
         exit $?
     elif [ "$COMMAND_DORAVEL" == 'fix' ]; then
         if [ -d "./bootstrap" ]; then
@@ -208,9 +217,151 @@ if [ ! -z "$COMMAND_DORAVEL" ]; then
             echo "No bootstrap or storage directories found"
         fi
         exit 0
+    elif [ "$COMMAND_DORAVEL" == 'doctor' ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
+            STATUS=0
+            if [ ! -d .doravel ]; then
+                STATUS=1
+                echo "❌ Directory .doravel not found"
+            else
+                echo "✅ Directory .doravel found"
+            fi
+            if [ ! -d vendor ]; then
+                STATUS=1
+                echo "❌ Directory vendor not found"
+            else
+                echo "✅ Directory vendor found"
+            fi
+            if [ ! -d node_modules ]; then
+                STATUS=1
+                echo "❌ Directory node_modules not found"
+            else
+                echo "✅ Directory node_modules found"
+            fi
+
+            ENVIRONMENTS=$(find . -maxdepth 1 -name ".env.*" | sed -E 's/^(\.\/)?\.env\.?//g' | sed 's/^$/local/g')
+            for ENVIROMENT in $ENVIRONMENTS; do
+                DOCKERCOMPOSE_NAME="docker-compose"
+                DOCKERFILE_PATH="Dockerfile"
+                ENV_PATH=".env"
+
+                if [ "$ENVIROMENT" != "local" ]; then
+                    DOCKERCOMPOSE_NAME="docker-compose.$ENVIROMENT"
+                    DOCKERFILE_PATH="Dockerfile.$ENVIROMENT"
+                    ENV_PATH=".env.$ENVIROMENT"
+                fi
+
+                DOCKERCOMPOSE_PATH=$(find . -maxdepth 1 -name "$DOCKERCOMPOSE_NAME.y*ml" | head -n 1)
+
+                if [ -z "$DOCKERCOMPOSE_PATH" ]; then
+                    STATUS=1
+                    echo "❌ File $DOCKERCOMPOSE_NAME.yaml not found"
+                else
+                    echo "✅ File $DOCKERCOMPOSE_NAME.yaml found"
+                fi
+
+                if [ ! -f "$ENV_PATH" ]; then
+                    STATUS=1
+                    echo "❌ File $ENV_PATH not found"
+                else
+                    echo "✅ File $ENV_PATH found"
+                fi
+
+                if [ ! -f "$DOCKERFILE_PATH" ]; then
+                    STATUS=1
+                    echo "❌ File $DOCKERFILE_PATH not found"
+                else
+                    echo "✅ File $DOCKERFILE_PATH found"
+                fi
+
+                if ! grep -qE "APP_ENV(\s+)?=(\s+)?$ENVIROMENT" $ENV_PATH; then
+                    STATUS=1
+                    echo "❌ APP_ENV=$ENVIROMENT not found in $ENV_PATH"
+                else
+                    echo "✅ APP_ENV=$ENVIROMENT found in $ENV_PATH"
+                fi
+
+                if [ ! -f .doravel/cron/$ENVIROMENT ]; then
+                    STATUS=1
+                    echo "❌ File .doravel/cron/$ENVIROMENT not found"
+                else
+                    echo "✅ File .doravel/cron/$ENVIROMENT found"
+                fi
+
+                if [ ! -f .doravel/php/$ENVIROMENT.ini ]; then
+                    STATUS=1
+                    echo "❌ File .doravel/php/$ENVIROMENT.ini not found"
+                else
+                    echo "✅ File .doravel/php/$ENVIROMENT.ini found"
+                fi
+
+                if [ ! -d .doravel/php/$ENVIRONMENT.d ]; then
+                    STATUS=1
+                    echo "❌ Directory .doravel/php/$ENVIRONMENT.d not found"
+                else
+                    echo "✅ Directory .doravel/php/$ENVIRONMENT.d found"
+                fi
+
+                if [ ! -f .doravel/supervisor/$ENVIROMENT.conf ]; then
+                    STATUS=1
+                    echo "❌ File .doravel/supervisor/$ENVIROMENT.conf not found"
+                else
+                    echo "✅ File .doravel/supervisor/$ENVIROMENT.conf found"
+                fi
+
+                if [ ! -d .doravel/supervisor/$ENVIRONMENT.d ]; then
+                    STATUS=1
+                    echo "❌ Directory .doravel/supervisor/$ENVIRONMENT.d not found"
+                else
+                    echo "✅ Directory .doravel/supervisor/$ENVIRONMENT.d found"
+                fi
+
+                if [ ! -f .doravel/nginx/$ENVIROMENT.conf ]; then
+                    STATUS=1
+                    echo "❌ File .doravel/nginx/$ENVIROMENT.conf not found"
+                else
+                    echo "✅ File .doravel/nginx/$ENVIROMENT.conf found"
+                fi
+
+                if [ ! -d .doravel/nginx/http.d ]; then
+                    STATUS=1
+                    echo "❌ Directory .doravel/nginx/http.d not found"
+                else
+                    echo "✅ Directory .doravel/nginx/http.d found"
+                fi
+
+                if [ ! -d .doravel/nginx/https.d ]; then
+                    STATUS=1
+                    echo "❌ Directory .doravel/nginx/https.d not found"
+                else
+                    echo "✅ Directory .doravel/nginx/https.d found"
+                fi
+            done
+            echo ""
+            echo "--------------------------------"
+            echo ""
+            if [ $STATUS -eq 0 ]; then
+                echo "✅ All files and directories found"
+            elif gum confirm "👨‍⚕️ do you want to fix it?"; then
+                gum spin --spinner dot --title "fixing" -- sleep 3
+                doravel fix
+                exit $?
+            fi
+
+            exit $STATUS
+        else
+            doravel x doravel doctor
+            exit $?
+        fi
+    elif [ "$COMMAND_DORAVEL" == 'install' ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
+            npm install
+            composer install
+        else
+            doravel x doravel install
+        fi
     elif [ "$COMMAND_DORAVEL" == 'setup' ]; then
-        echo "Command doravel"
-        if [ $DOCKER_CONTAINER -eq 1 ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
             recursive_cp /root/ .workflows/
             recursive_cp /root/ .workplan/
             recursive_cp /root/ .doravel/
@@ -218,19 +369,17 @@ if [ ! -z "$COMMAND_DORAVEL" ]; then
 
             touch database/database.sqlite
 
-            # npm install
-            # composer install
-            # artisan key:generate
-            # artisan storage:link
-
-            doravel local init
-            exit 0
+            doravel init && \
+            doravel example destroy && \
+            artisan key:generate && \
+            artisan storage:link && \
+            doravel install
+            exit $?
         else
             doravel x doravel setup
-            exit $?
         fi
     elif [ "$COMMAND_DORAVEL" == 'new' ]; then
-        if [ $DOCKER_CONTAINER -eq 1 ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
             DIRECTORY=$1
             shift 1
 
@@ -270,7 +419,7 @@ if [ ! -z "$COMMAND_ENVIRONMENT" ]; then
     echo "Command environment"
 
     if [ "$COMMAND_ENVIRONMENT" == 'init' ]; then
-        if [ $DOCKER_CONTAINER -eq 1 ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
             DOCKER_COMPOSE_FILE="$DOCKER_COMPOSE_NAME.yaml"
             STUBS_PATH="/root/.stubs"
 
@@ -293,23 +442,56 @@ if [ ! -z "$COMMAND_ENVIRONMENT" ]; then
             cp -vf /root/.doravel/supervisor/local.conf .doravel/supervisor/$ENV_NAME.conf
             yq '.services.app.build.dockerfile="'$DOCKERFILE_NAME'", .services.app.environment.APP_ENV="'$ENV_NAME'"' \
                 < "$STUBS_PATH/docker-compose.yaml" \
-                > $DOCKER_COMPOSE_FILE;
+                > "$DOCKER_COMPOSE_FILE";
 
             echo "created environment $ENV_NAME"
             exit 0
         else
-            doravel x doravel $ENV_NAME init
-            exit 0
+            doravel x doravel init
+            exit $?
         fi
     elif [ "$COMMAND_ENVIRONMENT" == "destroy" ]; then
-        rm -f $ENV_FILE
-        rm -f "$DOCKER_COMPOSE_NAME.yaml"
-        echo "destroyed environment $ENV_NAME"
-        exit 0
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
+            if [ "$ENV_NAME" == "local" ]; then
+                gum log --time rfc822 --level fatal "No se puede eliminar el entorno local."
+                exit 1
+            fi
+            if [ "$ENV_NAME" == "$APP_ENV" ] && [ $DORAVEL_ISOLATED -eq 0 ]; then
+                gum log --time rfc822 --level fatal "No se puede eliminar el entorno actual."
+                exit 1
+            fi
+            KEYWORD="destroy"
+            PASSWORD=$(gum input --placeholder "Escribe '$KEYWORD' para confirmar" --header "Estas seguro de eliminar el entorno ${ENV_NAME}?" --password --header.foreground=190)
+            if [ "$PASSWORD" = "$KEYWORD" ]; then
+                rm -vf "$ENV_FILE"
+                rm -vf "$DOCKER_FILE"
+                rm -vf "$DOCKER_COMPOSE_FILE"
+                rm -vf ".doravel/cron/$ENV_NAME"
+                rm -vf ".doravel/php/$ENV_NAME.ini"
+                rm -rf ".doravel/php/$ENV_NAME.d"
+                rm -rf ".doravel/nginx/$ENV_NAME.d"
+                rm -vf ".doravel/nginx/$ENV_NAME.conf"
+                rm -vf ".doravel/supervisor/$ENV_NAME.conf"
+                rm -rf ".doravel/supervisor/$ENV_NAME.d"
+                echo "👌 destroyed environment $ENV_NAME"
+                exit 0
+            else
+                gum log --time rfc822 --level error "No se ha confirmado la eliminacion."
+                echo ""
+                if gum confirm "quieres intentar de nuevo?"; then
+                    doravel $ENV_NAME destroy
+                    exit $?
+                fi
+                exit 1
+            fi
+        else
+            doravel x doravel $ENV_NAME destroy
+            exit $?
+        fi
     fi
 fi
 
-if [ ! -f $ENV_FILE ]; then
+if [ ! -f "$ENV_FILE" ]; then
     echo "the $ENV_FILE file does not exist"
     exit 0
 fi
@@ -336,7 +518,7 @@ container_exec() {
 }
 
 supervisorctl_exec() {
-    if [ $DOCKER_CONTAINER -eq 1 ]; then
+    if [ $DORAVEL_CONTAINER -eq 1 ]; then
         EXECUTABLE="supervisorctl --configuration /etc/supervisord.conf"
         COMMANDS=( "start" "stop" "restart" "status" "reload" "remove" "enable" "disable" )
 
@@ -433,7 +615,7 @@ if [ ! -z "$COMMAND_ENVIRONMENT" ]; then
             done
             exit 0
         elif [ "$1" == "shuffle" ]; then
-            if [ $DOCKER_CONTAINER -eq 1 ]; then
+            if [ $DORAVEL_CONTAINER -eq 1 ]; then
                 shuffle-ports --env $ENV_NAME
             else
                 docker run --rm -it -v .:/var/www $DORAVEL_IMAGE shuffle-ports --env $ENV_NAME
@@ -466,14 +648,14 @@ if [ ! -z "$COMMAND_ENVIRONMENT" ]; then
         supervisorctl_exec $@
         exit $?
     elif [[ " ${COMMANDS_ARTISAN[@]} " =~ " $COMMAND_ENVIRONMENT " ]]; then
-        if [ $DOCKER_CONTAINER -eq 1 ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
             artisan $COMMAND_ENVIRONMENT $@
         else
             container_exec artisan $COMMAND_ENVIRONMENT $@
         fi
         exit 0
     elif [[ " ${COMMANDS_BIN[@]} " =~ " $COMMAND_ENVIRONMENT " ]]; then
-        if [ $DOCKER_CONTAINER -eq 1 ]; then
+        if [ $DORAVEL_CONTAINER -eq 1 ]; then
             $COMMAND_ENVIRONMENT $@
         else
             container_exec $COMMAND_ENVIRONMENT $@
